import { CalendarDays, MapPin, BookOpen, Tag, Mic, Users, Sparkles, Bell, CalendarX, Images, Wrench } from 'lucide-react'
import { Link } from 'react-router-dom'
import { BookCover } from '../BookCover'
import { categories, eventDate, author, type EventBook, type LibraryEvent, type EventCategory } from '../../lib/events'
const icons = { NEW_ARRIVALS: BookOpen, BOOK_SALE: Tag, WORKSHOP: Wrench, AUTHOR_EVENT: Mic, READING_CLUB: Users, COMMUNITY_EVENT: Users, LIBRARY_PROGRAM: Sparkles, LIBRARY_NOTICE: Bell, CLOSURE: CalendarX, EXHIBITION: Images, OTHER: CalendarDays }
export function EventIcon({ category }: { category: EventCategory }) { const Icon = icons[category]; return <Icon size={24} strokeWidth={1.5} aria-hidden="true" /> }
export function EventMeta({ event }: { event: LibraryEvent }) { return <div className="event-meta"><span><CalendarDays size={16} />{eventDate(event.start_at)}{event.end_at && ` – ${eventDate(event.end_at)}`}</span>{event.location && <span><MapPin size={16} />{event.location}</span>}</div> }
export function RelatedBook({ book }: { book: EventBook }) {
  const palette = [...book.work_id].reduce((v, c) => v + c.charCodeAt(0), 0)
  return <Link to={'/book/' + encodeURIComponent(book.work_id)} className="event-book"><BookCover title={book.title || book.work_id} author={author(book)} paletteIndex={palette} variant="ring" /><h3>{book.title || 'Catalogue book'}</h3><p>{author(book)}</p></Link>
}
export function EventCard({ event }: { event: LibraryEvent }) { return <article className={`event-card ${event.featured ? 'is-featured' : ''}`}><div className="event-card-top"><span className="event-icon"><EventIcon category={event.category} /></span><span className="event-category">{categories[event.category]}</span>{event.featured && <span className="event-tag">Featured</span>}</div><h2><Link to={'/events/' + event.event_id}>{event.title}</Link></h2><p className="event-summary">{event.summary || 'Explore this library announcement.'}</p><EventMeta event={event} />{event.related_books.length > 0 && <p className="event-book-note"><BookOpen size={15} />{event.related_books.length} related {event.related_books.length === 1 ? 'book' : 'books'}</p>}<Link className="event-link" to={'/events/' + event.event_id}>View event →</Link></article> }
export function EventSkeleton() { return <div className="event-grid" aria-label="Loading events">{[0,1,2].map(i => <div className="event-skeleton" key={i}><div /><div /><div /></div>)}</div> }
export function EventPager({ page, count, size, change }: { page: number; count: number; size: number; change: (page: number) => void }) { return <div className="event-pager"><p>{count ? `${(page - 1) * size + 1}–${Math.min(page * size, count)} of ${count}` : '0 events'}</p><div><button disabled={page <= 1} onClick={() => change(page - 1)}>Previous</button><button disabled={page * size >= count} onClick={() => change(page + 1)}>Next</button></div></div> }
