import { useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useAuthStore } from '../store/useAuthStore'
import { eventApi, eventDate, categories, EVENTS_CHANGED, type EventPage, type LibraryEvent } from '../lib/events'
import { EventPager, EventSkeleton } from '../components/events/EventUI'
import { EventPublishSummary } from '../components/events/EventPublishSummary'
import { Modal } from '../components/StaffUI'
import './Staff.css'
import './Events.css'
export function ManageEventsPage() {
  const [params, setParams] = useSearchParams(), token = useAuthStore(s => s.token)
  const [reload, setReload] = useState(0), [search, setSearch] = useState(params.get('query') || '')
  const [result, setResult] = useState<{ key: string; data?: EventPage; error?: string }>({ key: '' })
  const [confirmation, setConfirmation] = useState<{ event: LibraryEvent; action: 'publish' | 'cancel' | 'archive' | 'delete' } | null>(null)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), lock = useRef(false)
  const query = params.toString(), key = `${token}:${query}:${reload}`, page = Math.max(1, Number(params.get('page')) || 1)
  useEffect(() => { const controller = new AbortController(); void eventApi.manage(query, controller.signal).then(data => { if (!controller.signal.aborted && useAuthStore.getState().token === token) setResult({ key, data }) }).catch(e => { if (!controller.signal.aborted) setResult({ key, error: e instanceof Error ? e.message : 'Unable to load events.' }) }); return () => controller.abort() }, [query, key, token])
  function filter(name: string, value: string) { const next = new URLSearchParams(params); if (value) next.set(name, value); else next.delete(name); next.delete('page'); setParams(next) }
  async function action() { if (!confirmation || lock.current) return; lock.current = true; setBusy(true); setError(''); try { await eventApi.action(confirmation.event.event_id, confirmation.action); if (useAuthStore.getState().token !== token) return; setConfirmation(null); setReload(v => v + 1); window.dispatchEvent(new Event(EVENTS_CHANGED)) } catch (e) { setError(e instanceof Error ? e.message : 'Action failed.') } finally { lock.current = false; setBusy(false) } }
  const data = result.key === key ? result.data : undefined
  return <div className="events-shell"><Link className="event-link" to="/events">← Events &amp; Announcements</Link><header className="events-heading"><div><span className="event-eyebrow">LIBRARY STAFF</span><h1>Manage Events</h1><p>Prepare announcements, publish programs and keep their history.</p></div><Link className="event-button primary" to="/staff/events/new">Create Event</Link></header>
    <div className="event-filters"><label>Status<select aria-label="Event status" value={params.get('status') || ''} onChange={e => filter('status', e.target.value)}><option value="">All statuses</option>{['DRAFT','PUBLISHED','CANCELLED','ARCHIVED'].map(v => <option value={v} key={v}>{v[0] + v.slice(1).toLowerCase()}</option>)}</select></label><label>Category<select aria-label="Event category" value={params.get('category') || ''} onChange={e => filter('category', e.target.value)}><option value="">All categories</option>{Object.entries(categories).map(([v, label]) => <option value={v} key={v}>{label}</option>)}</select></label><form onSubmit={e => { e.preventDefault(); filter('query', search.trim()) }}><label>Search events<input value={search} aria-label="Search events" maxLength={120} onChange={e => setSearch(e.target.value)} /></label><button className="event-button">Search</button></form></div>
    {(result.key === key && result.error) && <p role="alert">{result.error} <button className="event-button" onClick={() => setReload(v => v + 1)}>Retry</button></p>}
    {!data && !(result.key === key && result.error) ? <EventSkeleton /> : data && <><div className="event-manage-list">{data.events.map(event => <article className="event-manage-row" key={event.event_id}><div><span className={`event-status ${event.status.toLowerCase()}`}>{event.status}</span>{event.featured && <span className="event-tag">Featured</span>}<h2>{event.title}</h2><p>{categories[event.category]} · {eventDate(event.start_at)}</p><p className="event-muted">Created by {event.created_by?.email || event.created_by?.name || 'Unavailable staff account'} · Updated {eventDate(event.updated_at)}{event.updated_by?.email && ` by ${event.updated_by.email}`}</p></div><div className="events-actions">{event.status !== 'ARCHIVED' && <Link className="event-button" to={'/staff/events/' + event.event_id + '/edit'}>Edit</Link>}{event.status === 'DRAFT' ? <><button className="event-button primary" onClick={() => setConfirmation({ event, action: 'publish' })}>Publish</button><button className="event-button" onClick={() => setConfirmation({ event, action: 'delete' })}>Delete Draft</button></> : event.status !== 'ARCHIVED' && <>{event.status === 'PUBLISHED' && <button className="event-button" onClick={() => setConfirmation({ event, action: 'cancel' })}>Cancel Event</button>}<button className="event-button" onClick={() => setConfirmation({ event, action: 'archive' })}>Archive</button><Link className="event-button" to={'/events/' + event.event_id}>View</Link></>}{event.status === 'ARCHIVED' && <span className="event-muted">History retained</span>}</div></article>)}{!data.events.length && <div className="event-empty">No events match this view.</div>}</div><EventPager page={page} count={data.count} size={data.page_size} change={v => { const next = new URLSearchParams(params); next.set('page', String(v)); setParams(next) }} /></>}
    {confirmation && <Modal title={confirmation.action === 'publish' ? 'Publish this event?' : confirmation.action === 'delete' ? 'Delete this draft?' : confirmation.action === 'cancel' ? 'Cancel this event?' : 'Archive this event?'} busy={busy} onClose={() => setConfirmation(null)}>{confirmation.action === 'publish' ? <EventPublishSummary event={confirmation.event} /> : <p>{confirmation.event.title}</p>}<p>{confirmation.action === 'publish' ? 'It will become visible to library users and create a new-event signal.' : confirmation.action === 'delete' ? 'This unpublished draft will be permanently removed.' : confirmation.action === 'cancel' ? 'It will leave Upcoming. Its detail page will show that it was cancelled.' : 'It will be hidden from ordinary browsing. Staff history is retained.'}</p>{error && <p role="alert">{error}</p>}<div className="events-actions"><button className="event-button" disabled={busy} onClick={() => setConfirmation(null)}>Keep editing</button><button className="event-button primary" disabled={busy} onClick={() => void action()}>{busy ? 'Working…' : confirmation.action === 'delete' ? 'Delete Draft' : confirmation.action === 'publish' ? 'Publish event' : confirmation.action === 'cancel' ? 'Cancel event' : 'Archive event'}</button></div></Modal>}
  </div>
}
